In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np

In [3]:
L1=[1,2,3,4]

In [4]:
arr=np.array(L1)

In [9]:
print(arr)
type(L1)
type(arr)

[1 2 3 4]


numpy.ndarray

In [11]:
type(L1)

list

In [66]:
arr1=np.arange(0,10)

In [18]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr1=np.arange(0,10,step=2)

In [65]:
type(arr1)

numpy.ndarray

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
arr2=[6,7,8,9]

In [24]:
arr2[3:]

[9]

In [25]:
arr2=arr1
arr1[3:]=500
print(arr1)
print(arr2)

[  0   2   4 500 500]
[  0   2   4 500 500]


In [26]:
arr1=arr2.copy()
arr1[3:]=1500

In [27]:
print(arr1)
print(arr2)

[   0    2    4 1500 1500]
[  0   2   4 500 500]


In [28]:

arr=np.array([1,2,3,4,5,6])

In [29]:
arr[3]

4

In [64]:
type(arr)

list

In [50]:
arr = np.array([[1, 2, 3], [4,5,6,],[7,8,9]])


In [56]:
print(arr[2,1:])

[8 9]


In [69]:
arr2

array([[ True,  True, False, False, False, False, False, False, False,
        False]])